# Generated by Django 6.0.1 on 2026-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(default='products/default.jpg', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
