# Generated by Django 6.0.1 on 2026-02-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
