# Generated by Django 6.0.1 on 2026-02-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='deposited_money',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
