# Generated by Django 6.0.1 on 2026-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_purchases_deposited_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
