# Generated by Django 6.0.1 on 2026-01-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('count', models.IntegerField()),
                ('picture', models.ImageField(upload_to='picture/dishes')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('count', models.IntegerField()),
                ('picture', models.ImageField(upload_to='pictures/products')),
            ],
        ),
    ]
