# Generated by Django 6.0.1 on 2026-02-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weight', models.FloatField(verbose_name='Вес (г)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish_type', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/dishes')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('expiration_date', models.DateField(auto_now_add=True, null=True)),
                ('amount_cooked', models.PositiveIntegerField()),
                ('amount_sold', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес ингредиента в блюде')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', through='cook.Composition', to='cook.ingredient'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_intake', models.CharField(max_length=50, verbose_name='Прием пищи')),
                ('date', models.DateField()),
                ('dish1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pos1', to='cook.dish')),
                ('dish2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pos2', to='cook.dish')),
                ('dish3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pos3', to='cook.dish')),
                ('dish4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pos4', to='cook.dish')),
                ('dish5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pos5', to='cook.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('mark', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.dish')),
            ],
        ),
    ]
