# Generated by Django 6.0.1 on 2026-02-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cook', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='stock',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.dish'),
        ),
    ]
