# Generated by Django 6.0.1 on 2026-02-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес ингредиента в блюде')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weight', models.FloatField(verbose_name='Вес (г)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish_type', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/dishes')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_intake', models.CharField(max_length=50, verbose_name='Прием пищи')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposited_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_of_meal', models.DateField()),
                ('attendance', models.BooleanField(default=False)),
                ('food_intake', models.CharField(max_length=50)),
                ('type_of_purchase', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('mark', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='роль')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('amount_cooked', models.PositiveIntegerField()),
                ('amount_sold', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student_class', models.CharField(db_column='class', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО пользователя')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='cook.role')),
            ],
        ),
        migrations.DeleteModel(
            name='dishes',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.AddField(
            model_name='composition',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.dish'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', through='cook.Composition', to='cook.ingredient'),
        ),
        migrations.AddField(
            model_name='composition',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.ingredient'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.ingredient'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dish1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pos1', to='cook.dish'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dish2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pos2', to='cook.dish'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dish3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pos3', to='cook.dish'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dish4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pos4', to='cook.dish'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dish5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pos5', to='cook.dish'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cook.orderstatus'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.menu'),
        ),
        migrations.AddField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.dish'),
        ),
        migrations.AddField(
            model_name='stock',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.dish'),
        ),
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.student'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.student'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='cook.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cook.user'),
        ),
        migrations.AlterUniqueTogether(
            name='allergy',
            unique_together={('student', 'ingredient')},
        ),
    ]
