# Generated by Django 6.0.1 on 2026-02-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0002_allergy_composition_dish_ingredient_menu_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allergy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='student',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
