# Generated by Django 6.0.1 on 2026-02-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
