# Generated by Django 6.0.1 on 2026-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_ingredient_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.FloatField(),
        ),
    ]
