# Generated by Django 6.0.1 on 2026-02-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cook.dish'),
        ),
    ]
