# Generated by Django 6.0.1 on 2026-02-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_alter_review_student_delete_allergy_delete_purchases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
