# Generated by Django 6.0.1 on 2026-02-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
