# Generated by Django 6.0.1 on 2026-02-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0006_alter_stock_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expiration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
